### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by mauxuam** [pje/WavTap#45]
I am sorry but I have to insult u..
you did an alpha  and never updated it since last year !
you got somehow the attention of CDM so thuosands of ppl download and installed it...
when you go viral you can expect that the users will not know what is a terminal and how to use it...and ANYWAY the list of "nerd" commands that you put here as instructions is not working on my compute (latest ML).
as a developer ur support sucks.
the app sometime works, most of the time captures files with a VERY low volume in db even with volume slider full up.
There is plenty of problems, Soundflower is not working anymore...the volume of my audio card jumps up and down...I would love to be able to simply remove your piece of crap but I can't...
Did you get a job ? or are you still in the Nirvana for the CDM review ?
Please provide correct instructions on how to remove your code or if there is a way we should report you.

**Comment by Rockergmail** [comment]
@pje cool
