### ISSUE TITLE
 Kernel extensions signed with earlier versions of OS X are treated as unsigned by OS X v10.9.

### ISSUE THREAD

**Issue by ievergreen** [pje/WavTap#46]
https://developer.apple.com/library/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_9.html

Thank your for your hard work.
I'm waiting your new update version to figure it out.

**Comment by pje** [comment]
@ievergreen: thanks again for reporting this. Please read [the section of the new README that covers enabling unsigned kernel extensions](https://github.com/pje/WavTap#installation). If you're still up for it after reading that, pull master and re-install or use the installer from the [latest release](https://github.com/pje/WavTap/releases/download/0.3.0/WavTap.0.3.0.pkg).

**Comment by ievergreen** [comment]
Thanks for your recommendation. By the way I did this solution before.It's not unstable for Camfrog Video Chat. Sorry to tell you that I have moving to use Sound  Siphon. It's work properly for my DJ setting. Thanks again for solution and concerning every post here.
