### ISSUE TITLE
Yosemite can't make install

### ISSUE THREAD

**Issue by m1entus** [pje/WavTap#53]
When i am trying to make install kernel extension i am getting this error:

sudo chmod -R 700 /System/Library/Extensions/WavTap.kext
sudo chown -R root:wheel /System/Library/Extensions/WavTap.kext
sudo kextload -v /System/Library/Extensions/WavTap.kext
Requesting load of /System/Library/Extensions/WavTap.kext.
/System/Library/Extensions/WavTap.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
make[1]: *** [install] Error 71
make: *** [install-kext] Error 2

In other hand when i downloaded WavTap 0.2.0.pkg is working fine. I am trying to make own kerner audio device extension, could you help me ?

**Comment by SkylerLipthay** [comment]
[OS X 10.10 no longer allows for unsigned kernel extensions](http://lifepluslinux.blogspot.com/2014/10/loading-unsigned-kernel-extensions-on.html). I think the reason why the official WavTap package still works is because its .kext has been signed.

**Comment by pje** [comment]
@m1entus, @audiofilter, @SkylerLipthay: yep, that's exactly the problem. :\

I've updated the [Installation section of the README](https://github.com/pje/WavTap#installation) with a section about enabling unsigned kernel extensions. I'm sorry it's not a good answer, but it's not exactly a good situation either.

**Comment by pje** [comment]
I'm going to close this issue. If you've enabled `kext-dev-mode` and shit's still going wrong, open up a new issue, OK?
