### ISSUE TITLE
wavtap won't capture audio in yosemite

### ISSUE THREAD

**Issue by jmobb** [pje/WavTap#54]
am I crazy or does wav tap not work in the latest release of yosemite?

**Comment by pje** [comment]
No, you're probably not crazy. Check out the [install information in the updated README](https://github.com/pje/WavTap#installation); there have been changes to OSX as of yosemite that cripple non-signed kernel extensions.

**Comment by jmobb** [comment]
Ahh. That sucks. I guess there is no workaround then? Such an immensely useful tool.

**Comment by cksum** [comment]
Correct me if I'm wrong, but shouldn't the kext be installed to /Library/Extensions now rather than /System/Library/Extension to avoid having to disable the new security features in Yosemite and El Cap?
