### ISSUE TITLE
Retina Icon?

### ISSUE THREAD

**Issue by johnhamelink** [pje/WavTap#55]
Hey there, I know this issue is a bit "bikesheddy", but it'd be nice to have a retina icon!

Thanks
JH

**Comment by pje** [comment]
@johnhamelink: not bikesheddy at all! Actually retina icons are currently in master. I've just got to build a new release of the installer package. 

As you may have noticed, the issues have been piling up around here. :)

I haven't given WavTap the love it deserves for the last little bit. Going to try to do better (at the very least responding to new issues) from now on.

<3, pje

**Comment by johnhamelink** [comment]
Thanks @pje Looking forward to that crisp, clear icon in the near future :) Also say hi to the livestreamers who are reading this thread on my screen while listening to metallica with WavTap and OBS :smile:

**Comment by pje** [comment]
OK, closed by the latest release: https://github.com/pje/WavTap/releases/download/0.3.0/WavTap.0.3.0.pkg

**Comment by johnhamelink** [comment]
Excellent, thanks so much :+1: :smile:
