### ISSUE TITLE
Application selection not working

### ISSUE THREAD

**Issue by evanniedojadlo** [pje/WavTap#58]
I am sometimes unable to select WavTap within "Applications" and have to navigate to it using the arrow keys in order to actually load it.

Also, when successfully loaded I am seeing "Kernel Extension Not Loaded"

Platform details:
OS X Yosemite 10.10.3 (I am guessing that sudo nvram boot-args=kext-dev-mode=1 will resolve this?)

**Comment by pje** [comment]
@evanniedojadlo: If you're still on Yosemite, try re-running the installer.

**Comment by evanniedojadlo** [comment]
@pje Thanks, no longer seeing this issue. Closing out.
